#!/bin/bash
rsync -avz --delete \
  --exclude-from $HOME/fredym/workenv/tools/bk.d/bk-exclude \
  --include-from $HOME/fredym/workenv/tools/bk.d/bk-include \
  --exclude '*' \
  $HOME/ $HOME/Library/CloudStorage/Dropbox/aleph
