#!/bin/bash

title()
{
  b=$(tput bold)
  n=$(tput sgr0)

  echo
  echo "$b$1$n"
}


title "HOSTS:"
docker-machine ls

title "DISK USAGE:"
du -hd0 ~/Library/Containers/com.docker.docker | awk '{ print $1 }'

title "IMAGES:"
docker images --format "[{{.Size}}] {{.Repository}}:{{.Tag}}"

title "VOLUMES:"
docker volume ls

title "NETWORKS:"
docker network ls

title "CONTAINERS [IMAGES]:"
docker ps -a --no-trunc --format "[{{.Names}}] {{.Image}}"

title "CONTAINERS [STATUS]:"
docker ps -a --no-trunc --format "[{{.Names}}] {{.Command}} {{.Status}}"

title "CONTAINERS [MOUNTS]:"
docker ps -a --no-trunc --format "[{{.Names}}] {{.Mounts}}"
