#!/bin/bash
set -e

appname=$1
rails="docker run --rm -v $(pwd):/opt/workdir -w /opt/workdir fredym/rails rails"
bundle="docker run --rm -v $(pwd)/$appname:/opt/workdir -w /opt/workdir fredym/rails bundle"


# Create a new rails application
$rails new $appname --skip-bundle


# Adjust the Gemfile
sed -e "s|# gem 'therubyracer'|gem 'therubyracer'|" -i "" $appname/Gemfile
cat >> $appname/Gemfile <<EOL
# Use HAML for templates
gem 'haml-rails'
# Use Bootstrap for resposive layout
gem 'bootstrap-sass'
# Use Font Awesome and ionicons for iconography
gem 'font-awesome-rails'
gem 'font-ionicons-rails'
# Use FastClick to make following links in mobile browsers faster
gem 'fastclick-rails'
# Use jQuery DataTables to display tabular data
gem 'jquery-datatables-rails'
# Use Select2 for smarter select boxes
gem 'select2-rails'
# Use bootstrap-datepicker for date input
gem 'bootstrap-datepicker-rails'
# Use jquery-ui to improve user interface
gem 'jquery-ui-rails'
# Use bootstrap-wysihtml5 for textarea editing
gem 'bootstrap-wysihtml5-rails'
# Use Moment.js for date manipulation in the browser
gem 'momentjs-rails'
# Use Date Range Picker for date range input
gem 'bootstrap-daterangepicker-rails'
EOL


# Update Gemfile.lock
$bundle install --local


# Make the README a Markdown file
mv $appname/README.rdoc $appname/README.md


# Move the sqlite files to db/data/
sed -e "s|db/|db/data/|" -i "" $appname/config/database.yml
sed -e "s|db/|db/data/|" -i "" $appname/.gitignore


# Add Docker support
cat > $appname/Dockerfile <<EOL
FROM fredym/rails
EOL

cat > $appname/.dockerignore <<EOL
.dockerignore
.git
.gitignore
Dockerfile
db/data
log/*
tmp
EOL


# Customize application.js
cat > $appname/app/assets/javascripts/application.js <<EOL
//= require jquery2
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require fastclick
//= require dataTables/jquery.dataTables
//= require select2
//= require select2_locale_es
//= require bootstrap-datepicker/core
//= require bootstrap-datepicker/locales/bootstrap-datepicker.es.js
//= require jquery-ui
//= require bootstrap-wysihtml5
//= require bootstrap-wysihtml5/locales/es-ES
//= require moment
//= require moment/es.js
//= require daterangepicker
EOL


# Customize application.css and convert into SCSS
rm $appname/app/assets/stylesheets/application.css
cat > $appname/app/assets/stylesheets/application.scss <<EOL
@import "bootstrap";
@import "bootstrap-sprockets";
@import "font-awesome";
@import "ionicons";
@import "dataTables/jquery.dataTables";
@import "select2";
@import "bootstrap-datepicker";
@import "jquery-ui";
@import "bootstrap-wysihtml5/bootstrap3-wysihtml5";
@import "daterangepicker-bs3";
EOL


# Convert application.html.erb into HAML
rm $appname/app/views/layouts/application.html.erb
cat > $appname/app/views/layouts/application.html.haml <<EOL
!!!
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    %title= (@page_title or 'Page Title')
  %body
    = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
EOL


# Clean routes.rb
cat > $appname/config/routes.rb <<EOL
Rails.application.routes.draw do
end
EOL


# Clean seeds.rb
cat /dev/null > $appname/db/seeds.rb
