#!/bin/bash
set -e

appname=$1
rails="docker run --rm -v $(pwd):/opt/workdir -w /opt/workdir fredym/rails rails"
bundle="docker run --rm -v $(pwd)/$appname:/opt/workdir -w /opt/workdir fredym/rails bundle"


# Create a new rails application
$rails new $appname --skip-bundle


# Adjust the Gemfile
sed -e "s|# gem 'therubyracer'|gem 'therubyracer'|" -i "" $appname/Gemfile
cat >> $appname/Gemfile <<EOL
# Use HAML for templates
gem 'haml-rails'
# Use Bootstrap for resposive layout
gem 'bootstrap-sass'
# Use Font Awesome and ionicons for iconography
gem 'font-awesome-rails'
gem 'font-ionicons-rails'
# Use FastClick to make following links in mobile browsers faster
gem 'fastclick-rails'
# Use jQuery DataTables to display tabular data
gem 'jquery-datatables-rails'
# Use Select2 for smarter select boxes
gem 'select2-rails'
# Use bootstrap-datepicker for date input
gem 'bootstrap-datepicker-rails'
# Use jquery-ui to improve user interface
gem 'jquery-ui-rails'
EOL


# Update Gemfile.lock
$bundle install --local


# Make the README a Markdown file
mv $appname/README.rdoc $appname/README.md


# Move the sqlite files to db/data/
sed -e "s|db/|db/data/|" -i "" $appname/config/database.yml
sed -e "s|db/|db/data/|" -i "" $appname/.gitignore


# Add Docker support
cat > $appname/Dockerfile <<EOL
FROM fredym/rails
EOL

cat > $appname/.dockerignore <<EOL
.dockerignore
.git
.gitignore
Dockerfile
db/data
log/*
tmp
EOL
